version = "1.0"

[main]

services = ["__APP__"]

    [main.customization]

        [main.customization.instanceType]
        ask = "Mono user instance"
        type = "boolean"
        help = "If this instance is mono user, the feed list will be the same for all users"
        bind = "instance_type()"

