packaging_format = 2

id = "petrolette"
name = "Petrolette"
description.en = "The news reader that doesn't know you"
description.fr = "La page d'actu qui ne sait rien de toi"

version = "1.6.0~ynh2"

maintainers = ["oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
demo = "https://petrolette.space"
code = "https://framagit.org/yphil/petrolette"
website = "https://framagit.org/yphil/petrolette"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.3.0"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/petrolette"

    [install.mono_user]
    ask.fr = "Cette instance est elle mono utilisateur ?"
    ask.en = "Is this instance mono user ?"
    help.fr = "Cette instance ne proposera qu'une seule selection de flux, la même pour tous les visiteurs"
    help.en = "This instance will have the same rss selection for any visitor visiting the page"
    type = "boolean"
    default = true

    [install.init_main_permission]
    help.fr = "Cette page sera accessible par n'importe qui. En revanche, la configuration reste personnelle"
    help.en = "The page will be accessible by anyone."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://framagit.org/yphil/petrolette/-/archive/v1.6.0/petrolette-v1.6.0.tar.gz"
        sha256 = "25cff32873fb643882a1b43681842a646d4e46a9802da2ab086ab29f770b7d7e"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
