#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="The news reader that doesn't know you" --log="/var/log/$app/$app.log"

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL PETROLETTE
#=================================================
ynh_script_progression "Installing application using node..."

pushd $install_dir
# set port in configuration file
	sed -i "/HTTP_PORT/s/[0-9]*[0-9]/$port/" package.json
	sed -i "/HTTPS_PORT/s/[0-9]*[0-9]/$port_https/" package.json
	# use custom home value to avoid bower storing values in root and have right errors
	if [ $mono_user -eq 1 ] ; then
	    ynh_config_add --template="petrolette.config.json" --destination="petrolette.config.json"
	fi
	if [ "$path" != "/" ] ; then
        sed -i "s|\$.get(\"/feed\", {|\$.get(\"feed\", {|" public/js/PTL.feed.js

	fi
	[[ -v HOME ]] && TMP_HOME=$HOME
	HOME=$(pwd)
	export NODE_ENV=production

	ynh_hide_warnings npm install --ignore-scripts
	[[ -v TMP_HOME ]] && HOME=$TMP_HOME || unset HOME
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action=start --log_path=systemd --wait_until="Pétrolette HTTP Server running on port"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
