#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action=stop --log_path=systemd --line_match="Stopped"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=1

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir"
fi

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=3

# Create a dedicated NGINX config
ynh_add_nginx_config

ynh_install_nodejs --nodejs_version=$NODEJS_VERSION

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="The news reader that doesn't know you"

#=================================================
# SPECIFIC UPGRADE
#=================================================
# UPDATE APP
#=================================================
ynh_script_progression --message="Upgrading the app..." --weight=5

pushd $install_dir
# set port in configuration file
        sed -i "/HTTP_PORT/s/[0-9]*[0-9]/$port/" package.json
        sed -i "/HTTPS_PORT/s/[0-9]*[0-9]/$port_https/" package.json
    if [ "$path" != "/" ] ; then
        sed -i "s|\$.get(\"/feed\", {|\$.get(\"feed\", {|" public/js/PTL.feed.js 
    fi

	[[ -v HOME ]] && TMP_HOME=$HOME
        HOME=$(pwd)
        ynh_use_nodejs
        ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH NODE_ENV=production $ynh_npm install --ignore-scripts
        [[ -v TMP_HOME ]] && HOME=$TMP_HOME || unset HOME
popd

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=3

ynh_systemd_action --service_name=$app --action="start" --log_path=systemd --line_match="Pétrolette HTTP Server running on port"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
